---
permalink: /cn_version/
title: "个人简介"
author_profile: true
redirect_from: 
 - /cn_version/
 - /cn_version.html
---

## 尹德云

### 个人简介

​		尹德云，现任哈尔滨工业大学（深圳）经济与管理学院**副教授**，博士毕业于**日本东京大学工学部技术经营战略学**，担任联合国下属专门机构**世界知识产权组织（WIPO）经济与数据分析司创新经济处**研究员、顾问**、**东京大学先端科学技术研究中心高级客座研究员。在加盟WIPO之前，曾任日本通商产业省下属经济产业研究所（RIETI）研究助理。

​        主要研究方向为技术创新战略、创新经济地理和知识产权大数据分析，研究主题涉及基于机器学习的专利和科研文献大数据挖掘、全球创新集群和创新网络、知识产权与经济增长、气候技术研发创新与国际技术转移等。论文发表在**Nature Climate Change**、Journal of Informetrics 及 Scientometrics等国际顶级杂志上以及牛津大学出版社的图书系列中。参与编写和发布了**《世界知识产权报告2019：创新的地理格局》、《世界知识产权报告2022：创新的方向》，被翻译为五国语言全球发行**，并受到新华社采访解读我国国际创新合作新趋势和特点。2022年**主持发布了WIPO发展研究报告——**Innovation ecosystem and catch-up in developing countries等；**主持国家自然科学基金1项**，以及多项广东省、深圳市政府、大连市政府等知识产权和政府决策咨询项目。

​        获得“**深圳市海外高层次人才”**、南山区“领航人才”称号，担任**国家知识产权局“世界银行全球营商环境与知识产权”项目咨询专家、广东省市场监督管理局（知识产权局）**、广州商标审查中心（广东知识产权公共服务中心）、深圳市科创委项目评审专家，中国（深圳）知识产权保护中心海外维护援助专家等等。应邀在美国国家经济研究所（NBER）、经济合作与发展组织（OECD）、美国专利及商标局（USPTO）、日本国家科技政策研究所（NISTEP）、东京大学、一桥大学、洛桑联邦理工学院（EPFL）研讨会做主题报告多次，研究成果受到国际学术界的广泛肯定，担任**技术经济学会技术孵化与创新生态分会理事**、NBER创新信息企划首批专家组成员。担任 Research Policy, Regional Studies, Scientometrics等国际知名期刊和会议的审稿人，并担任2020年在挪威举行的创新经济地理（GEOINNO 2020）机器学习与经济地理分论坛主席。

### 研究方向

- 知识产权大数据挖掘；机器学习、文本挖掘与社交网络分析等技术在创新研究上的应用
- 技术创新管理，创新战略（人才流动及其技术网络），知识产权战略
- 创新经济地理（创新产业集群和全球创新网络，区域创新系统）
- 科技政策（知识产权保护与赶超战略，高新技术人才战略、产业园区等）

### 博士招生

​        欢迎对创新经济管理、科技创新政策和知识产权大数据分析感兴趣的同学报考研究生和博士！有编程经验的同学优先。申请请将个人简历和简短介绍发到邮箱：yindeyunut@gmail.com 



## 教育和工作经历

### 教育背景

|      时间       |           学位            |   学校   |
| :-----------: | :-------------------------: | :------: |
| 2016.04~2019.03 |  **Ph.D.** 技术经营战略   | 东京大学 |
| 2011.09~2014.06 | **M.A.** 科技哲学与科技史 | 北京大学 |
| 2005.09~2010.07 |       **B.A.** 哲学       | 武汉大学 |

### 研究与工作经历

|      时间       |                      机构                      |      职位      |
| :-------------: | :--------------------------------------------: | :------------: |
|    2024.04~     |          东京大学先端科学技术研究中心          | 高级客座研究员 |
|    2024.05~     |      哈尔滨工业大学（深圳），经济管理学院      |     副教授     |
| 2020.01~2024.04 |      哈尔滨工业大学（深圳），经济管理学院      |    助理教授    |
|    2023.03~     | 联合国世界知识产权组织（WIPO）经济与数据分析司 |      顾问      |
| 2019.02~2023.02 |   联合国世界知识产权组织（WIPO）经济与统计司   |     研究员     |
| 2017.05~2019.02 |          日本经济产业研究所（RIETI）           |    研究助理    |



## 学术成果

### 论文

- Jingjing Jiang, **Deyun Yin**, Zhuoluo Sun, Bin Ye, Nan Zhou (2024), 全球甲烷技术创新趋势及其与甲烷排放日益增大的差距，**Nature Climate Change**, 14, 393–401 (IF=31.4, Nature大子刊，唯一通讯作者) 

  - 受到Nature官方报道：Jingjing JIANG & **Deyun YIN** (2024), Trends in the global invention and international diffusion of methane abatement technologies, Nature Portfolio

- **Deyun Yin,** Zhao Wu, Sotaro Shibayama (2023) , **科学研究中的风险测度，Journal Of Informetrics** **,** 17(3).  (IF=3.4, JCR Q1)  

  - 全球首篇利用机器学习和文本挖掘方法预测科研风险的文章。

- **Deyun Yin**,  Wu Zhao, Kazuki Yokota, Kuniko Matsumoto, Sotaro Shibayama (2023),**识别科学的要素新颖性，Plos One**.18(6). (IF=2.9, JCR Q1)

- Sotaro Shibayama, **Deyun Yin**, & Kunico Matsumoto. (2021). **基于词嵌入的科学新颖性测量. Plos One**, 16(7). (IF=2.9, JCR Q1)

- **Deyun Yin,**Kazuyuki Motohashi, Jianwei Dang，**中国专利发明者消歧（1985-2016）**（英文），**Scientometrics**, (IF: 3.5, JCR Q1) 

  - 该文作为全球首篇采用机器学习方法系统对中国专利发明者进行消歧的研究，针对2018年版CNIPA中国专利全库650万专利中的180万姓名进行消歧，划分了中国、日本和海外姓名，成功识别出400万中国发明者并做了分析，在美国国家经济研究所（NBER）和美国专利与商标局汇报。

- Charles ZHANG，**尹德云**，元桥一之，**中国互联网公司的创新战略与技术赶超：来自专利文本挖掘的证据**（英文）, **PICMET** 2019 (EI检索, *为通讯作者)*

- Georgios Tsiachtsiras, **Deyun Yin\*,** Ernest Miguelez, Rosina Moreno (2024), 思想的列车：中国的高速铁路与创新, **Industry & Innovation**. (在审)


### 著作

- 唐杰，**尹德云**，戴欣等(2023)，**《新时代深圳经济高质量发展研究》**，北京：中国社会科学文献出版社。
- **Deyun Yin**, Julio Raffo, Jie Tang (2022), **全球创新热点：创新生态系统与发展中国家的赶超：来自深圳的证据**，世界知识产权组织，日内瓦。（英文）
- WIPO (2022). World Intellectual Property Report 2022: The Direction of Innovation. World Intellectual Property Organization. **《世界知识产权报告2022：创新的方向》**. 世界知识产权组织，日内瓦. （被翻译为联合国六国语言）
- Carsten Fink, Julio  Raffo, Intan Hamdan-Livramento, Maryam Zehtabchi, **Deyun Yin**     (2019). **《世界知识产权报告2019：创新的地理格局：区域热点，全球网络》**. 世界知识产权组织，日内瓦. （被翻译为联合国六国语言）
- Massimiliano  Coda-Zabetta, Christian Chacua, Francesco Lissoni, Ernest Miguelez, Julio Raffo, **Deyun Yin** (2022). **全球集群创新网络中的国际合作，资本和移民，《变动世界中的跨国创新：参与者，区域和政策》**，牛津大学出版社。（英文）

### 工作论文

- Gema Lax Martínez, Helena Saenz de Juano-i-Ribes, **Deyun Yin**, Bruno Le Feuvre, Intan Hamdan-Livramento, Kaori Saito and Julio Raffo (2021), **世界（发明者）性别词典WGND 2.0**. WIPO working paper series 64. 

- Ernest Miguelez, Julio Raffo, Christian Chacua, Massimiliano Coda-Zabetta, **Deyun Yin,** Francesco Lissoni, Gianluca Tarasconi (2019), **连接：知识的全球化、区域创新热点与全球创新网络**（英文），世界知识产权组织工作论文系列。

- 尹德云和元桥一之(2018)，**基于机器学习的中国发明者姓名消歧及其地理流动（1985-2016）**（英文），经济产业研究所工作论文系列，18-E-018, RIETI, 2018/03. 

- 尹德云和元桥一之(2019)，**中国发明者的流动及其对区域经济的影响**（英文），东京大学博士论文数据库，2018.08  创新研究所暑期论坛上报告（一桥大学）

- 尹德云和元桥一之(2019)，**中国技术人才的组织间流动**（英文），东京大学博士论文数据库， 2018.11  中国创新系统2018论坛上报告（同济大学）

  

### 研究报告

- 中国专利发明者流动趋势分析（1985-2020）
- 基于专利大数据的全国城市海洋科创发展现状与趋势1985-2023
- 深圳近十年科技投入与产出绩效分析（2013-2022）



## 数据库和代码资源

### 代码

- **[全球甲烷专利筛选与分析](https://github.com/DeyunYinWIPO/global_methane), Nature Climate Change**, 2024
- **[基于词向量的论文和专利原创性计算代码](https://github.com/DeyunYinWIPO/Novelty_Science_Text). PLOS ONE**，2023
- **[基于词嵌入模型和SVM的科研风险度量](https://github.com/DeyunYinWIPO/science_risk). Journal of Informetrics**，2023
- **[基于词向量的论文和专利原创性计算代码](https://github.com/DeyunYinWIPO/Novelty). PLOS ONE**，2021
- **[Genderit]**(https://github.com/IES-platform/r4r_gender): 根据姓名识别全球性别的算法
  - 基于WIPO的[**World Gender-Name Dictionary (WGND)全球姓名-性别词典** ](https://github.com/IES-platform/r4r_gender/blob/main/wgnd/README.md): 该词典囊括了**全球195个国家**的**2500万**以上的姓名-性别记录。 


### 专利数据库

- 全球专利数据库
  - 扩展版PATSTAT全球专利数据库
    - 根据专利家族和CNIPA、WIPO、JPO、USPTO等专利局原始数据填充了缺失信息完整版PATSTAT
    - [全球发明者姓名-性别词典WGND 2.0]](https://github.com/IES-platform/r4r_gender/blob/main/wgnd/README.md)
  - 全球PCT专利数据库
    - PCT专利申请人-发明者地理信息数据库
    - PCT专利发明者消歧数据库
- 各局专利数据
  - 全样本CNIPA中国专利数据库
    - 中国专利地理信息编码数据库
    - 中国专利城市-区县数据库
    - 中国专利发明者消歧数据库
    - 中国专利发明者流动数据库
    - 中国专利质量数据库
  - 日本JPO专利局数据库
    - 日本专利地址信息数据库
    - 日本专利地理信息编码数据库(最新上线)
    - 日本专利发明人消歧数据库
  - Others 

### 科研论文数据库

- 全球科研论文数据库
  - 全球科研论文地理信息编码（Geocoding）数据库
  - 全球科研论文论文词嵌入(Word Embedding)模型数据库
  - 全球科研论文论文指标数据库，核心指标包括
    - 论文新颖性Novelty
    - 论文影响力 Impact
    - 论文和项目研发风险 Risk
    - 其他。。。（稍后发布）



数据库资源访问和合作请联系邮件：yindeyunut@gmail.com



##   教学

| **时间**        | **课程**               | **授课对象**                       |
| --------------- | ---------------------- | ---------------------------------- |
| 2024.11~        | 技术转移与科技成果转化 | 哈工大商学院MBA课程                |
| 2024.09~        | 知识产权与创新创业管理 | 哈工大（深圳）辅修课程             |
| 2024.02         | 商标，品牌与区域经济   | 广东商标中心合作开发中英粤三语课程 |
| 2023.12~        | 货币、银行与金融市场   | 哈工大深圳硕士课程                 |
| 2023.11~        | 货币金融学             | 哈工大（深圳）硕士课程             |
| 2023.03  ~      | 创新经济学             | 哈工大（深圳）本科课程             |
| 2022.10         | 微观经济学前沿专题     | 哈工大（深圳）硕士课程             |
| 2021.09  ~      | 应用微观经济学研究专题 | 哈工大（深圳）本科课程             |
| 2020.09  ~      | 创新经济与管理         | 哈工大（深圳）博士课程             |
| 2020.09  ~      | 空间经济学             | 哈工大（深圳）本科课程             |
| 2020.06~        | 中国经济发展与转型     | 哈工大（深圳）硕士课程             |
| 2018.04~2018.0  | 专利文本挖掘           | 东京大学硕士、博士课程             |
| 2012.03~2013.02 | 科学，技术与社会       | 北京大学硕士课程（助教）           |
| 2012.09~2013.02 | 科学技术史             | 北京大学元培学院本科生（助教）     |

 

## 研究项目

###  **研究项目（主持）**

| 时间            | 项目                                                         |
| --------------- | ------------------------------------------------------------ |
| 2025.01-2027.12 | **基于文本挖掘和机器学习的突破性创新专利识别方法及其在区域突破性创新中的应用研究**，自然科学基金青年项目，项目号72404069，在研 |
| 2024.05-2024.12 | **广东省科技创新报告****2024****，**广东省市场监督管理局（知识产权局），在研 |
| 2024.03-2024.05 | **粤港澳商标品牌与区域经济国际课程体系建设，**广州商标审查写作中心（广东省知识产权开发与服务中心），已结题 |
| 2022.06-2022.11 | **深圳市近十年科技投入与科技产出研究**，深圳市决策咨询委员会，已结题 |
| 2022.08-2023.07 | **大连加快海洋强市路径研究**，中国科学院海洋所，已结题 <br>成果：基于专利大数据的全国城市海洋科创发展现状与趋势 |
| 2021.01~2023.12 | **基于机器学习的中国专利质量衡量**，深圳市高层次人才引进科研启动经费，已结题，**主持****。** |
| 2020.02-2022.12 | **联合国世界知识产权组织全球创新发展研究——“探索发展中国家的区域创新生态体系”**，  国际合作项目，已结题，**主要负责人之一**   WIPO 与新加坡知识产权局、巴西国家工业知识产权局、巴西应用经济研究所(IPEA)、白俄罗斯国家法律信息中心、法国国家科学研究中心(CNRS)、新加坡国立大学、哈尔滨工业大学（深圳）等机构的政府官员和学者合作开展科研项目。 |
| 2021.11-2022.06 | **深圳市突破性创新专利识别及实现路径探究**，哈工大（深圳）人文社会科学发展专项基金决策咨询研究专项，已结题 |
| 2021.11-2022.06 | **全球创新网络中的深圳，**哈工大（深圳）人文社会科学发展专项基金决策咨询研究专项，已结题 |
| 2020.01-2022.12 | **基于机器学习的发明者姓名消歧及科技人才流动研究**，校级科研启动经费项目，已结题 |

###  **研究项目（参与）** 

| 时间            | 项目                                                         |
| --------------- | ------------------------------------------------------------ |
| 2023.06-2023.12 | **深圳探索提升知识产权全链条保护水平研究**，深圳市人民政府发展研究中心，已结题 |
| 2023.11-2024.01 | **深圳市数字创业生态体系研究，**深圳市科技创新战略研究和技术转移促进中心，已结题 |
| 2022.05-2022.12 | **《深圳这十年》特辑编撰研究**，深圳市社会科学院，已结题     |
| 2021.01-2024.12 | **地方政府创新与扩散中的政策话语研究，**国家社科基金一般项目, 21BZZ101,已结题 |
| 2020.08~2021.02 | **粤港澳大湾区发展研究**，万科企业股份有限公司，横向项目，参与，已结题。 |
| 2020.06-2020.11 | **基于高质量发展的南山区现代产业体系，构建和产业政策创新研究**，深圳市南山区，横向项目，已结题，参与。 |
| 2017.05~2019.02 | **基于研究者信息的中日开放式创新比较研究**，国家自然科学基金-日本政府JSPS国际合作项目（国际），编号:71711540044，已结题，日方主要参与者。 |
| 2017.04~2018.12 | **关于IoT的发展与创新生态系统的实证研究**, 日本经济产业研究所（RIETI），结题 |



## 学术与公共服务

### 公共服务

|   时间   |                          内容                          |
| :------: | :----------------------------------------------------: |
| 2024.02~ | 国家知识产权局“世界银行全球营商环境与知识产权”项目专家 |
| 2023.08~ |         广东省市场监督管理局（知识产权局）专家         |
| 2022.05~ |        深圳知识产权专家、深圳科创委项目评审专家        |
| 2021.07~ |      中国（深圳）知识产权保护中心海外维护援助专家      |

### 学术服务

|   时间   |                             内容                             |
| :------: | :----------------------------------------------------------: |
| 2021.11  |           担任中国管理学年会2021知识产权分会场主席           |
| 2021.01  | 担任在挪威举行的创新经济地理（GEOINNO 2020）机器学习与经济地理分论坛主席 |
| 2018.11~ | Research Policy, China Economic Review, Scientometrics, Regional Studies, Technology Forcasting and Social Change, Scientometrics等杂志审稿人 |

###  社会培训

- 2024.09  中国（深圳）知识产权中心  知识产权经济与大数据分析专题培训
- 2024.08  华南理工大学              WIPO 知识产权暑期课程
- 2024.01 中国（深圳）知识产权中心  知识产权大数据挖掘与运用专题培训
- 2023.11 国家行政学院（深圳）      梅州市知识产权专题培训 
- 2023.09 广东省市场监督管理局      广东省地方党政领导干部高质量发展专题培训
- 2023.08 广东省市场监督管理局      广东省地方党政领导干部知识产权专题培训
- 2023.01 同济大学                 上海国际知识产权学院知识产权国际化人才培训



[学校主页](https://faculty.hitsz.edu.cn/yindeyun).

